### ISSUE TITLE
Make Docker (and other?) actions fork-safe

### ISSUE THREAD

**Issue by jhkennedy** [ASFHyP3/actions#47] opened 2022-12-07 23:05 UTC
The docker build action always tries to push to GHCR, and thus will fail for forks as they don't have permission to push to GHCR. We should either figure out how to allow pushes from forks (maybe not the best idea from a sec perspective!) or skip the push action for forks.

**Comment by jhkennedy** [comment] 2023-03-10 20:29
Fixed in #57

**Comment by jtherrmann** [comment] 2023-03-10 22:29
Example of pushing and tagging successfully (on a non-fork repo): https://github.com/ASFHyP3/hyp3-ci/actions/runs/4388321365/jobs/7684692901

**Comment by jtherrmann** [comment] 2023-03-10 23:34
I merged a PR from my fork of `hyp3-ci` but it looks like there are still failing actions: https://github.com/ASFHyP3/hyp3-ci/actions

I'm not sure if I'm taking the correct steps to reproduce the original bug. I'm reopening this issue until we've confirmed that the fix works.

**Comment by jhkennedy** [comment] 2023-03-11 01:03
Confirm it does work as expected here: https://github.com/ASFHyP3/hyp3-ci/pull/7

*If* you use the `GITHUB_TOKEN`; will update the README

**Closed** 2023-04-17 22:07 UTC
